{
 "title": "Cluster Nodes",
 "description": "Cluster node metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Node", "query": "netdata_info" }
  ]
 },
 "panels": [
  {
   "title": "Lowest Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, netdata_system_uptime_seconds_average{instance=~\"($node_id)\"} )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_info{job=~\"netdata-($node_id)\"})"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MB_average{instance=~\"($node_id)\"})"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(netdata_cgroup_writeback_MB_average{instance=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"received\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "bottomk(1, sum(netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"sent\"}))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Cluster Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"reads\"}))",
     "legendFormat": "Reads"
    },
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"writes\"}))",
     "legendFormat": "Writes "
    }
   ]
  },
  {
   "title": "Node Load Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{dimension=\"load1\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Free /",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_disk_space_GB_average{family=\"/\",dimension=~\"avail\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Free /var/lib/docker",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(netdata_disk_space_GB_average{family=\"/var/lib/docker\",dimension=~\"avail\",job=~\"netdata-($node_id)\"},\"job\",\"$1\",\"job\",\"netdata-(.*)\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest CPU Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"}) by (job) )"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, sum(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\".*\"}) by (instance))"
    }
   ]
  },
  {
   "title": "Lowest Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_system_ram_MB_average{job=~\"netdata-($node_id)\"} ) by (job) * sum(netdata_system_ram_MB_average{dimension=~\"free|cached\",job=~\"netdata-($node_id)\"} ) by (job) ) )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_system_ram_MB_average{instance=~\"($node_id)\"}) by (instance) * sum(netdata_system_ram_MB_average{dimension=~\"free|cached\",instance=~\"($node_id)\"}) by (instance) ) )"
    }
   ]
  },
  {
   "title": "Lowest Free /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_disk_space_GB_average{family=\"/\", instance=~\"($node_id)\"}) by (instance) * sum(netdata_disk_space_GB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"($node_id)\"} ) by (instance) ) )",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, 100 / sum(netdata_disk_space_GB_average{family=\"/\", instance=~\"($node_id)\"}) by (instance) * sum(netdata_disk_space_GB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"($node_id)\"} ) by (instance) )"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"received\",instance=~\"($node_id)\"}",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "netdata_net_net_kilobits_persec_average{family=~\"eth.*|en.*\",dimension=\"sent\",instance=~\"($node_id)\"}",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"($node_id)\"}) by (instance) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Wait per Operation",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_await_ms_per_operation_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "sum(netdata_disk_await_ms_per_operation_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Write {{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (Used)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_ram_MB_average{dimension=\"used\",instance=~\"($node_id)\"}",
     "legendFormat": "Memory: {{instance}}"
    }
   ]
  },
  {
   "title": "Node CPU I/O Wait",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_cpu_cpu_percentage_average{dimension=\"iowait\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory (Cached)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "netdata_system_ram_MB_average{dimension=\"cached\",instance=~\"($node_id)\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_files_open_files_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_files_open_files_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Sockets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Open Pipes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_apps_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_apps_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_users_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance) + sum(netdata_groups_pipes_open_pipes_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(label_replace(engine_daemon_engine_info{instance=~\"($node_id):9323\"},\"instance\",\"$1\",\"instance\",\"(.*):9323\")  ) by (instance, kernel, os, version)"
    },
    {
     "expr": "count(sum(netdata_cgroup_cpu_percent_average{job=~\"netdata-($node_id)\"}) by (instance,chart)) by (instance)"
    },
    {
     "expr": "label_replace(swarm_node_manager{instance=~\"($node_id):9323\"}, \"instance\", \"$1\", \"instance\", \"(.*):9323\")"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort(count(netdata_cgroup_writeback_MB_average{instance=~\"$node_id\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_network_actions_seconds_count{instance=~\"($node_id):9323\"}[1m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_container_actions_seconds_count{instance=~\"($node_id):9323\"}[1m]) ) ) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"veth.*\",dimension=\"received\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "IN {{instance}}"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{family=~\"veth.*\",dimension=\"sent\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "OUT {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance))",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family!=\"fd0\",family!=\"/etc/resolv.conf\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance) )",
     "legendFormat": "Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_cgroup_cpu_percent_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "CPU: {{instance}}"
    }
   ]
  },
  {
   "title": "Docker Container Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family=~\"/var.*|/pxd.*\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance))",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "round(sum(netdata_disk_ops_operations_persec_average{family=~\"/var.*|/pxd.*\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance))",
     "legendFormat": "Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Container Memory usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_cgroup_mem_MB_average{instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Memory: {{instance}}"
    }
   ]
  },
  {
   "title": "Container Disk IO",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{family=~\"/pxd.*|/var.*\",dimension=\"reads\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Reads {{instance}}"
    },
    {
     "expr": "sum(netdata_disk_io_kilobytes_persec_average{family=~\"/pxd.*|/var.*\",dimension=\"writes\",instance=~\"($node_id)\"}) by (instance)",
     "legendFormat": "Writes {{instance}}"
    }
   ]
  }
 ]
}