{
 "title": "Containers",
 "description": "Container metrics",
 "tags": [ "docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Node", "query": "netdata_info" }
  ]
 },
 "panels": [
  {
   "title": "Container Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_stack_namespace=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\" ) ) by (node_id) * on (node_id) group_left(state) swarm_node_info{instance=~\"($node_id):9323\"})"
    }
   ]
  },
  {
   "title": "Cluster Stacks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_stack_namespace=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\" ) * on (node_id) group_left(state) swarm_node_info{job=~\"dockerd-($node_id)\"}) by (container_label_com_docker_stack_namespace) )"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_swarm_service_name=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\") * on(node_id) group_left(state) swarm_node_info{job=~\"dockerd-($node_id)\"}) by (container_label_com_docker_swarm_service_id))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(netdata_cgroup_cpu_percent_average{job=~\"netdata-($node_id)\"}) by (chart,instance))"
    }
   ]
  },
  {
   "title": "Top CPU usage by Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(netdata_cgroup_cpu_percent_average{instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)(.*).cpu\") ) by (chart,instance) )",
     "legendFormat": "{{instance}} {{chart}}"
    }
   ]
  },
  {
   "title": "Top Memory usage by Container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(netdata_cgroup_mem_MB_average{instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)(.*).mem\") ) by (chart,instance) )",
     "legendFormat": "{{instance}} {{chart}}"
    }
   ]
  },
  {
   "title": "Top CPU usage by Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(netdata_cgroup_cpu_percent_average{instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)([a-zA-Z0-9_]+).*\") ) by (chart) )",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Top Memory usage by Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(netdata_cgroup_mem_MB_average{instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)([a-zA-Z0-9_-]+).*\") ) by (chart) )",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Failed Health Checks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(irate(engine_daemon_health_checks_failed_total{job=~\"dockerd-($node_id)\"}[5m]) ) ) by (instance)",
     "legendFormat": "{{instance}} failed"
    }
   ]
  },
  {
   "title": "Top Network received by Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(label_replace(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\",dimension=\"received\",instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)([a-zA-Z0-9_-]+).*\") ) by (chart) )",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Running Docker Services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(sum(label_replace(container_tasks_state{state=\"running\",container_label_com_docker_swarm_service_name=~\".+\"}, \"node_id\", \"$1\", \"container_label_com_docker_swarm_node_id\", \"(.*)\") * on(node_id) group_left(state) swarm_node_info{job=~\"dockerd-($node_id)\"}) by (container_label_com_docker_swarm_service_id) )",
     "legendFormat": "Running services"
    }
   ]
  },
  {
   "title": "Top Network transmitted by Service",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "- bottomk(10, sum(label_replace(netdata_net_net_kilobits_persec_average{chart=~\"cgroup_.*\",dimension=\"sent\",instance=~\"$node_id\"}, \"chart\", \"$2\", \"chart\", \"(cgroup_system.slice_portworx.|cgroup_)([a-zA-Z0-9_-]+).*\") ) by (chart) )",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Docker Swarm Nodes",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(label_replace(engine_daemon_engine_info{instance=~\"($node_id):9323\"},\"instance\",\"$1\",\"instance\",\"(.*):9323\")  ) by (instance, kernel, os, version)"
    },
    {
     "expr": "count(sum(netdata_cgroup_cpu_percent_average{instance=~\"($node_id)\"}) by (instance,chart)) by (instance)"
    },
    {
     "expr": "label_replace(swarm_node_manager{instance=~\"($node_id):9323\"}, \"instance\", \"$1\", \"instance\", \"(.*):9323\")"
    }
   ]
  }
 ]
}