{
 "title": "Containers (node_exporter+dockerd+cadvisor)",
 "description": "Container metrics",
 "tags": [
  "cadvisor",
  "dockerd",
  "node_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "node_load1" },
   {
    "name": "node_9323",
    "label": "Node:9323",
    "query": "query_result(label_replace(node_load1{instance=~\"$node\"}, \"instance\", \"$1:9323\", \"instance\", \"(.*):[0-9]+\"))"
   },
   {
    "name": "node_no_port",
    "label": "Node_no_port",
    "query": "query_result(label_replace(node_load1{instance=~\"$node\"}, \"instance\", \"$1\", \"instance\", \"(.*):[0-9]+\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(swarm_node_info{instance=~\"$node_9323\"})"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(container_tasks_state{instance=~\"$node_no_port\",state=\"running\",container_label_com_docker_stack_namespace=~\".+\"}) by (container_label_com_docker_stack_namespace) )"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(container_tasks_state{instance=~\"$node_no_port\",state=\"running\",container_label_com_docker_swarm_service_name=~\".+\"}) by (container_label_com_docker_swarm_service_id))"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node_no_port\"})"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_health_checks_failed_total{instance=~\"$node_9323\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, avg by (container_label_com_docker_swarm_task_name) (rate(container_cpu_usage_seconds_total{instance=~\"$node_no_port\",container_label_com_docker_swarm_task_name!=\"\"}[60s])) * 1024)",
     "legendFormat": "{{container_label_com_docker_swarm_task_name}}"
    }
   ]
  },
  {
   "title": "Top Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(container_network_receive_bytes_total{name=~\".+\",instance=~\"$node_no_port\"}[1m])) by (name,instance))",
     "legendFormat": "IN: {{instance}} - {{name}}"
    },
    {
     "expr": "-topk(1, sum(rate(container_network_transmit_bytes_total{name=~\".+\",instance=~\"$node_no_port\"}[1m])) by (name,instance))",
     "legendFormat": "OUT: {{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, ceil(sum(rate(container_fs_reads_total{instance=~\"$node_no_port\", name=~\".+\"}[1m])) by (instance,name)) > 0)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Top Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(container_memory_usage_bytes{instance=~\"$node_no_port\",name=~\".+\"}) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Top Service CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, avg by (container_label_com_docker_swarm_service_name) (rate(container_cpu_usage_seconds_total{instance=~\"$node_no_port\",container_label_com_docker_swarm_service_name!=\"\"}[60s]) * 1024))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Top Service Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\".+\",instance=~\"$node_no_port\"}[1m]) > 100000 ) by (container_label_com_docker_swarm_service_name)) ",
     "legendFormat": "IN: {{container_label_com_docker_swarm_service_name}}"
    },
    {
     "expr": "-topk(2, sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\".+\",instance=~\"$node_no_port\"}[1m]) > 100000 ) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "OUT: {{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(container_fs_reads_bytes_total{instance=~\"$node_no_port\",name=~\".+\"}[1m])) by (name, instance))",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Top Service Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name!=\"\",instance=~\"$node_no_port\"}) by (container_label_com_docker_swarm_service_name))",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, 100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(container_network_receive_bytes_total{name=~\".+\",instance=~\"$node_no_port\"}[1m]) > 100000) by (instance))",
     "legendFormat": "IN: {{instance}}"
    },
    {
     "expr": "-topk(1,sum(rate(container_network_transmit_bytes_total{name=~\".+\",instance=~\"$node_no_port\"}[1m]) > 100000) by (instance))",
     "legendFormat": "OUT: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(1, ceil(sum(rate(container_fs_writes_total{instance=~\"$node_no_port\",name=~\".+\"}[1m])) by (name,instance) > 0 ))",
     "legendFormat": " {{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_network_actions_seconds_count[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Node Running Containers",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node_no_port\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"e.*\",instance=~\"$node\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(node_network_transmit_bytes_total{device=~\"e.*\",instance=~\"$node\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Top Container Storage Write Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(container_fs_writes_bytes_total{instance=~\"$node_no_port\",name=~\".+\"}[1m])) by (name, instance) > 0)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_container_actions_seconds_count[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Running Docker and OCI Containers",
   "type": "table",
   "gridPos": { "h": 50, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "container_tasks_state{id!~\"/|/docker|/system.slice.*|/user.slice.*\", instance=~\"$node_no_port\" ,state=\"running\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}