{
 "title": "Nodes (node_exporter+dockerd+cadvisor)",
 "description": "Cluster node metrics",
 "tags": [
  "cadvisor",
  "docker",
  "node_exporter"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "node_load1" },
   {
    "name": "node_no_port",
    "label": "Node",
    "query": "query_result(label_replace(node_load1{instance=~\"$node\"}, \"instance\", \"$1\", \"instance\", \"(.*):[0-9]+\"))"
   },
   {
    "name": "node_9323",
    "label": "Node:9323",
    "query": "query_result(label_replace(node_load1{instance=~\"$node\"}, \"instance\", \"$1:9323\", \"instance\", \"(.*):[0-9]+\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "Lowest Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - topk(1, node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_load1{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node_no_port\"})"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_health_checks_failed_total{instance=~\"$node_9323\"}[5m])))"
    }
   ]
  },
  {
   "title": "Top Node Load Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2,node_load1{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{device=~\"e.*\",instance=~\"$node\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(increase(node_network_transmit_bytes_total{device=~\"e.*\",instance=~\"$node\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Top Node Storage Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(node_disk_reads_merged_total{instance=~\"$node\"}[2m])) by (instance)) < 2000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Storage Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(node_disk_read_bytes_total{instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_reads_total{instance=~\"$node_no_port\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_reads_bytes_total{instance=~\"$node_no_port\"}[2m])) by (instance)) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, 100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(node_network_receive_bytes_total{device=~\"e.*\",instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "-topk(1, sum(rate(node_network_transmit_bytes_total{device=~\"e.*\",instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Storage Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3 ,sum(rate(node_disk_writes_completed_total{instance=~\"$node\"}[2m])) by (instance)) < 2000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Storage Write Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(node_disk_written_bytes_total{instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_writes_total{instance=~\"$node_no_port\"}[2m])) by (instance))",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Write Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_writes_bytes_total{instance=~\"$node_no_port\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest CPU Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))) )"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, ((100 / node_memory_MemTotal_bytes{instance=~\"$node\"}) * node_memory_MemFree_bytes{instance=~\"$node\"}) * 100)"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, ((100 / node_memory_MemTotal_bytes{instance=~\"$node\"}) * node_memory_MemFree_bytes{instance=~\"$node\"}) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Free /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, ((100 / node_filesystem_size_bytes{instance=~\"$node\"}) * node_filesystem_avail_bytes{instance=~\"$node\"}))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, 100 / node_filesystem_size_bytes{instance=~\"$node\"} * node_filesystem_avail_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg by (instance,name) (rate(container_cpu_usage_seconds_total{instance=~\"$node_no_port\"}[60s]) * 1024 * 60) / on (instance,name) (container_spec_cpu_shares) / 60 * 100)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, rate(container_network_receive_bytes_total{instance=~\"$node_no_port\"}[1m]) > 0)",
     "legendFormat": "IN: {{instance}}"
    },
    {
     "expr": "-topk(1, rate(container_network_transmit_bytes_total{instance=~\"$node_no_port\"}[1m]) > 0)",
     "legendFormat": "OUT: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_disk_io_time_seconds_total{instance=~\".*\"}[1m]))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(node_filesystem_files{instance=~\"$node\"} - node_filesystem_files_free{instance=~\"$node\"}) by (instance,device))",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Top Container Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum(container_memory_usage_bytes{instance=~\"$node_no_port\",id=\"/\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU IO Wait",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[1m]))) * 100) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node /",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(3, node_filesystem_avail_bytes{mountpoint=\"/\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Memory Used",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(2,sum(node_memory_MemTotal_bytes{instance=~\"$node\"} - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node_no_port\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_network_actions_seconds_count{instance=~\"$node_9323\"}[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Top Node CPU System",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[1m]))) * 100) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node /var/lib/docker",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(3,node_filesystem_free_bytes{mountpoint=\"/var/lib/docker\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node Memory Available",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(2,sum(node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_container_actions_seconds_count{instance=~\"$node_9323\"}[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Top Node CPU User",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[1m]))) * 100) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Steal",
   "type": "graph",
   "description": "Amount of CPU time stolen by the hypervisor for other VMs",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"steal\"}[1m]))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Soft/IRQ",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=~\"irq|softirq\"}[1m]))) * 100) > 0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Nice",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"nice\"}[1m]))) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(label_replace(engine_daemon_engine_info{instance=~\"$node_9323\"},\"instance\",\"$1:9100\",\"instance\",\"(.*):[0-9]+\")) by (instance, kernel, version)"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[1m]))) * 100"
    },
    {
     "expr": "label_replace(swarm_node_manager{instance=~\"$node_9323\"}, \"instance\", \"$1:9100\", \"instance\", \"(.*):[0-9]+\")"
    },
    {
     "expr": "label_replace(label_replace(sum(label_replace(node_uname_info{instance=~\"$node\"},\"instance\",\"$1:9100\",\"instance\",\"(.*):[0-9]+\")) by (instance, release, sysname), \"os\", \"$1\", \"sysname\", \"(.*)\"), \"kernel\", \"$1\", \"release\", \"(.*)\")"
    },
    {
     "expr": "count(label_replace(container_last_seen{instance=~\"$node_no_port\"}, \"instance\", \"$1:9100\", \"instance\", \"(.*)\")) by (instance)"
    }
   ]
  }
 ]
}