{
 "title": "Nodes (netdata+dockerd+cadvisor)",
 "description": "Cluster node metrics",
 "tags": [
  "docker",
  "netdata",
  "cadvisor"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": "netdata_info" },
   {
    "name": "node_9323",
    "label": "Node:9323",
    "query": "query_result(label_replace(netdata_info{instance=~\"$node\"}, \"instance\", \"$1:9323\", \"instance\", \"(.*)\"))"
   }
  ]
 },
 "panels": [
  {
   "title": "Lowest Node Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, netdata_system_uptime_seconds_average{instance=~\"$node\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_info{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(netdata_system_ram_MiB_average{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Failed Containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ceil(increase(engine_daemon_health_checks_failed_total{instance=~\"$node_9323\"}[5m]) ) )"
    }
   ]
  },
  {
   "title": "Top Node Load Factor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2,{dimension=\"load1\",instance=~\"$node\"} > 0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$node\",family=~\"eth.*|en.*\",dimension=\"received\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(netdata_net_net_kilobits_persec_average{instance=~\"$node\",family=~\"eth.*|en.*\",dimension=\"sent\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Top Node Storage Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(netdata_disk_ops_operations_persec_average{dimension=\"reads\",instance=~\"$node\"}) by (instance)) < 2000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Storage Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 2 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(netdata_disk_io_KiB_persec_average{dimension=\"reads\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Reads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_reads_total{instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Read Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 2 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_reads_bytes_total{instance=~\"$node\"}[2m])) by (instance)) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, 100 - (avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"$node\"}) by (instance)))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top LAN Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, sum(rate(netdata_net_net_kilobits_persec_average{instance=~\"$node\",family=~\"eth.*|en.*\",dimension=\"received\"}[1m])) by (instance))",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "-topk(1, sum(rate(netdata_net_net_kilobits_persec_average{instance=~\"$node\",family=~\"eth.*|en.*\",dimension=\"sent\"}[1m])) by (instance))",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Node Disk Write Operations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, -sum(netdata_disk_ops_operations_persec_average{dimension=\"writes\",instance=~\"$node\"}) by (instance)) < 2000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Storage Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "-topk(3, sum(netdata_disk_io_KiB_persec_average{instance=~\"$node\"}) by (instance)) < 2000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_writes_total{instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Storage Write Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(rate(container_fs_writes_bytes_total{instance=~\"$node\"}[2m])) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest CPU Free",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"$node\"}) by (instance))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, sum(netdata_cpu_cpu_percentage_average{dimension=\"idle\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, 100 / sum(netdata_system_ram_MiB_average{instance=~\"$node\"}) by (instance) * sum(netdata_system_ram_MiB_average{dimension=~\"free|cached\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "floor( bottomk(1, 100 / sum(netdata_system_ram_MiB_average{instance=~\"$node\"}) by (instance) * sum(netdata_system_ram_MiB_average{dimension=~\"free|cached\",instance=~\"$node\"}) by (instance) ) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Free /",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "bottomk(1, 100 / sum(netdata_disk_space_GiB_average{family=\"/\", instance=~\"$node\"}) by (instance) * sum(netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"$node\"} ) by (instance) ) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bottomk(1, 100 / sum(netdata_disk_space_GiB_average{family=\"/\", instance=~\"$node\"}) by (instance) * sum(netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail|cached\",instance=~\"$node\"} ) by (instance) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg by (instance,name) (rate(container_cpu_usage_seconds_total{instance=~\"$node\"}[60s]) * 1024 * 60) / on (instance,name) (container_spec_cpu_shares) / 60 * 100)",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(1, rate(container_network_receive_bytes_total{instance=~\"$node\"}[1m]) > 0)",
     "legendFormat": "IN: {{instance}}"
    },
    {
     "expr": "-topk(1, rate(container_network_transmit_bytes_total{instance=~\"$node\"}[1m]) > 0)",
     "legendFormat": "OUT: {{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Disk IO Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(1, (avg by (instance) (rate(netdata_disk_util___of_time_working_average{instance=~\".*\"}[1m]))) < 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Banned IPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(netdata_jail_in_jail_IPs_average)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Container Memory Used",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,sum(container_memory_usage_bytes{instance=~\"$node\",id=\"/\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(netdata_apps_files_open_files_average{instance=~\"$node\"}) by (instance) + sum(netdata_users_files_open_files_average{instance=~\"$node\"}) by (instance) + sum(netdata_apps_sockets_open_sockets_average{instance=~\"$node\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"$node\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"$node\"}) by (instance) + sum(netdata_apps_pipes_open_pipes_average{instance=~\"$node\"}) by (instance) + sum(netdata_users_pipes_open_pipes_average{instance=~\"$node\"}) by (instance) + sum(netdata_groups_pipes_open_pipes_average{instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Open Files",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(netdata_apps_files_open_files_average{instance=~\"$node\"}) by (instance,dimension) + sum(netdata_users_files_open_files_average{instance=~\"$node\"}) by (instance,dimension))",
     "legendFormat": "{{instance}} - {{dimension}}"
    }
   ]
  },
  {
   "title": "Top Node Open Pipes",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(netdata_apps_pipes_open_pipes_average{instance=~\"$node\"}) by (instance) + sum(netdata_users_pipes_open_pipes_average{instance=~\"$node\"}) by (instance) + sum(netdata_groups_pipes_open_pipes_average{instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Open Sockets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(2, sum(netdata_apps_sockets_open_sockets_average{instance=~\"$node\"}) by (instance) + sum(netdata_users_sockets_open_sockets_average{instance=~\"$node\"}) by (instance) + sum(netdata_groups_sockets_open_sockets_average{instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU IO Wait",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, sum(netdata_cpu_cpu_percentage_average{dimension=\"iowait\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node /",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(3, netdata_disk_space_GiB_average{family=\"/\",dimension=~\"avail\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node Memory Used",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 24 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, netdata_system_ram_MiB_average{dimension=\"used\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{instance=~\"$node\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Network Actions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_network_actions_seconds_count[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Top Node CPU System",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg(netdata_cpu_cpu_percentage_average{dimension=\"system\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node /var/lib/docker",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(3, netdata_disk_space_GiB_average{family=\"/var/lib/docker\",dimension=~\"avail\",instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Lowest Node Memory Available",
   "type": "graph",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 27 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(2, sum(netdata_system_ram_MiB_average{dimension=~\"free|cached|buffers\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Docker Container Actions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ceil(rate(engine_daemon_container_actions_seconds_count[1m]))) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Top Node CPU User",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg(netdata_cpu_cpu_percentage_average{dimension=\"user\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Steal",
   "type": "graph",
   "description": "Amount of CPU time stolen by the hypervisor for other VMs",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg(netdata_cpu_cpu_percentage_average{dimension=\"steal\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Soft/IRQ",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg(netdata_cpu_cpu_percentage_average{dimension=~\"irq|softirq\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Node CPU Nice",
   "type": "graph",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(3, avg(netdata_cpu_cpu_percentage_average{dimension=\"nice\",instance=~\"$node\"}) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "100 - avg(netdata_cpu_cpu_percentage_average{dimension=\"idle\"}) by (instance)"
    },
    {
     "expr": "sum(label_replace(engine_daemon_engine_info,\"instance\",\"$1\",\"instance\",\"(.*):9323\")  ) by (instance, kernel, os, version)"
    },
    {
     "expr": "label_replace(swarm_node_manager, \"instance\", \"$1\", \"instance\", \"(.*):9323\")"
    },
    {
     "expr": "count(container_last_seen) by (instance)"
    }
   ]
  }
 ]
}