{
 "title": "Portworx Volume Status",
 "tags": [ "portworx" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "volumename",
    "label": "Volume Name",
    "query": "label_values(px_volume_usage_bytes,volumename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Replication (HA) Level",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sort(px_volume_halevel)", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Volume Sizes",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "px_volume_capacity_bytes",
     "legendFormat": "{{volumename}} ( {{volumeid}} ) via {{instance}}"
    }
   ]
  },
  {
   "title": "Volume Usage Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc((px_volume_usage_bytes/px_volume_capacity_bytes)*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    {
     "format": "bytes",
     "label": "Bytes/second read (-) / write (+)"
    }
   ],
   "targets": [
    {
     "expr": "topk(5, px_volume_writethroughput{volumename=~\"$volumename\"})",
     "legendFormat": "Write: {{volumename}}"
    },
    {
     "expr": "bottomk(5, px_volume_readthroughput{volumename=~\"$volumename\"})",
     "legendFormat": "Read: {{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Depth IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(5, px_volume_depth_io{volumename=~\"$volumename\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, (px_volume_usage_bytes/px_volume_capacity_bytes)*100 )",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume IOPs",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "IO/second read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "topk(5, px_volume_iops{volumename=~\"$volumename\"}) ",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top bytes used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "topk(5, px_volume_usage_bytes)", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Lowest Bytes Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(5, px_volume_capacity_bytes - px_volume_usage_bytes)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, px_volume_vol_read_latency_seconds{volumename=~\"$volumename\"})",
     "legendFormat": "Read: {{volumename}}"
    },
    {
     "expr": "- bottomk(5, px_volume_vol_write_latency_seconds{volumename=~\"$volumename\"})",
     "legendFormat": "Write: {{volumename}}"
    }
   ]
  }
 ]
}