{
 "title": "Portworx Cluster Status",
 "tags": [ "portworx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size)-min(px_cluster_status_storage_nodes_online)"
    }
   ]
  },
  {
   "title": "Cluster Members",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size)"
    }
   ]
  },
  {
   "title": "Storage  Nodes Online",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(px_cluster_status_storage_nodes_online)"
    }
   ]
  },
  {
   "title": "Quorum Health",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(px_cluster_status_cluster_size)/count(px_cluster_status_cluster_quorum)"
    }
   ]
  },
  {
   "title": "Top CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage" }
   ],
   "targets": [
    {
     "expr": "topk(10, px_cluster_cpu_percent)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top Network IOs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    {
     "format": "short",
     "label": "IO\\second received(+)\\sent(-)"
    }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(px_network_io_received_bytes[5m]) )",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "bottomk(5, 0-irate(px_network_io_bytessent[5m]) )",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Active Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(px_disk_stats_io_seconds[5m])",
     "legendFormat": "{{node}} - {{disk}}"
    }
   ]
  },
  {
   "title": "Top Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "bottomk( 5, 0-irate(px_disk_stats_write_bytes[5m]) )",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "topk(5, irate(px_disk_stats_read_bytes[5m]) )",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  },
  {
   "title": "Pending IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Pending IO" }
   ],
   "targets": [
    { "expr": "px_cluster_pendingio", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Storage Space Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(px_cluster_disk_utilized_bytes/px_cluster_disk_available_bytes)*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk IOs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bottomk(5, 0-irate(px_disk_stats_write_seconds[5m]) )",
     "legendFormat": "Write: {{instance}}"
    },
    {
     "expr": "topk(5, irate(px_disk_stats_read_seconds[5m]) )",
     "legendFormat": "Read: {{instance}}"
    }
   ]
  }
 ]
}