{
 "title": "Portworx Volumes Status",
 "tags": [ "portworx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "volumename",
    "label": "Volume Name",
    "query": "label_values(px_volume_usage_bytes,volumename)"
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Replication (HA) Level",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sort(px_volume_halevel)", "legendFormat": "{{volumename}}" }
   ]
  },
  {
   "title": "Lowest Bytes Free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "bottomk(2, px_volume_capacity_bytes{volumename=~\"($volumename)\"} - px_volume_usage_bytes{volumename=~\"($volumename)\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume IOPs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(2, px_volume_iops{volumename=~\"($volumename)\"}) > 0",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Usage",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    { "expr": "sort(px_volume_usage_bytes)" }
   ]
  },
  {
   "title": "Top Volume Read Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": " topk(3, px_volume_readthroughput{volumename=~\"($volumename)\"} )",
     "legendFormat": "Write: {{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(2, (px_volume_usage_bytes{volumename=~\"($volumename)\"}/px_volume_capacity_bytes{volumename=~\"($volumename)\"})*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Fill",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sort_desc((px_volume_usage_bytes/px_volume_capacity_bytes)*100)",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Write Throughput",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(3, px_volume_writethroughput{volumename=~\"($volumename)\"} ) > 0",
     "legendFormat": "Write: {{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(2, px_volume_vol_read_latency_seconds{volumename=~\"$volumename\"}) > 0",
     "legendFormat": "Read: {{volumename}}"
    },
    {
     "expr": "- topk(2, px_volume_vol_write_latency_seconds{volumename=~\"$volumename\"}) < 0",
     "legendFormat": "Write: {{volumename}}"
    }
   ]
  },
  {
   "title": "Volume Size",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "px_volume_capacity_bytes",
     "legendFormat": "{{volumename}} ( {{volumeid}} ) via {{instance}}"
    }
   ]
  },
  {
   "title": "Top bytes used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(2, px_volume_usage_bytes{volumename=~\"($volumename)\"})",
     "legendFormat": "{{volumename}}"
    }
   ]
  },
  {
   "title": "Top Volume Depth IO",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(2, px_volume_depth_io{volumename=~\"($volumename)\"}) > 0",
     "legendFormat": "{{volumename}}"
    }
   ]
  }
 ]
}