{
 "title": "Prometheus 2.0 Stats",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Alertmanager Active Alerts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Alerts Suppressed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(alertmanager_alerts{state=\"suppressed\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Expired Silences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(alertmanager_silences{state=\"expired\"})"
    }
   ]
  },
  {
   "title": "Write-ahead-logs Corruptions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_wal_corruptions_total{job=~\".*_prometheus\"})"
    }
   ]
  },
  {
   "title": "Prometheus Notifications Sent",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_sent_total)"
    }
   ]
  },
  {
   "title": "Alertmanager Active Silences",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(alertmanager_silences{state=\"active\"})"
    }
   ]
  },
  {
   "title": "Alertmanager Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(prometheus_notifications_alertmanagers_discovered{job=~\".*_prometheus\"})"
    }
   ]
  },
  {
   "title": "Query Durations",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_engine_query_duration_seconds{job=~\".*_prometheus\", quantile=\"0.99\"}",
     "legendFormat": "{{slice}}_p99"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\".*prometheus\"})",
     "legendFormat": "p8s process resident memory"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\".*_prometheus\"})",
     "legendFormat": "virtual memory"
    }
   ]
  },
  {
   "title": "Compaction Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(prometheus_tsdb_compaction_duration_bucket{job=~\".*_prometheus\"}[5m])) by (le))",
     "legendFormat": "duration-{{p99}}"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "compactions"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_failed_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "failed"
    },
    {
     "expr": "irate(prometheus_tsdb_compactions_triggered_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "triggered"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Samples Appended",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(prometheus_tsdb_head_samples_appended_total{job=~\".*_prometheus\"}[5m]))",
     "legendFormat": "samples"
    }
   ]
  },
  {
   "title": "Head Block GC Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_gc_duration_seconds{job=~\".*_prometheus\",quantile=\"0.99\"}",
     "legendFormat": "duration-p99"
    },
    {
     "expr": "irate(prometheus_tsdb_head_gc_duration_seconds_count{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "collections"
    }
   ]
  },
  {
   "title": "Rule Group Eval Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(prometheus_rule_group_duration_seconds{job=~\".*_prometheus\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Active Appenders",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_active_appenders{job=~\".*_prometheus\"})",
     "legendFormat": "active_appenders"
    },
    {
     "expr": "sum(process_open_fds{job=~\".*_prometheus\"})",
     "legendFormat": "open_fds"
    }
   ]
  },
  {
   "title": "Reload Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_reloads_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "reloads"
    },
    {
     "expr": "rate(prometheus_tsdb_reloads_failures_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Rule Group Eval Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_rule_group_iterations_missed_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "missed"
    },
    {
     "expr": "rate(prometheus_rule_group_iterations_total{job=~\".*_prometheus\"}[5m])",
     "legendFormat": "iterations"
    }
   ]
  },
  {
   "title": "Head Chunks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\".*prometheus\"})",
     "legendFormat": "chunks"
    }
   ]
  },
  {
   "title": "Blocks Loaded",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_blocks_loaded{job=~\".*_prometheus\"}",
     "legendFormat": "blocks"
    }
   ]
  }
 ]
}